version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: social_network_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: social_network_db
      DB_USER: miuser
      DB_PASSWORD: mipass

  profile-service:
    build: ./profile-service
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: social_network_db
      DB_USER: miuser
      DB_PASSWORD: mipass


  posts-service:
    build: ./posts-service
    ports:
      - "3003:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: social_network_db
      DB_USER: miuser
      DB_PASSWORD: mipass

  api-gateway:
    build: ./api-gateway
    depends_on:
      - auth-service
      - profile-service
      - posts-service
    ports:
      - "8000:3000"  # mapear puerto externo 8000 al interno 3000 del gateway


volumes:
  postgres-data:
